# -*- mode: ruby -*-
# vi: set ft=ruby :

$memory = 1024
$cores = 2

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.synced_folder "./data", "/vagrant_data"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = $memory
    vb.cpus = $cores
  end

  
end
